# Site settings
title: Dustin Zeisler
email: dustinzeisler+dustinzeislercom@gmail.com
display_email: dustinzeisler@gmail.com
description: > #
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dustinzeisler.com" # the base hostname & protocol for your site
twitter_username: dustinzeisler
github_username:  zeisler
linkedin_username: dzeisler
paginate: 5
# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts
